# -*- coding: utf-8 -*-
"""qa_selenium_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQwwA_w2p8HBwZ6ikdINhcogtIgCnnWb
"""

pip install selenium

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time

# Initialize WebDriver
driver_path = "C:\\Users\\ritik\\Downloads\\chromedriver.exe"  # Replace with the path to your ChromeDriver
service = Service(driver_path)
driver = webdriver.Chrome(service=service)

try:
    # Step 1: Navigate to the Selenium Playground Table Search Demo
    url = "https://www.lambdatest.com/selenium-playground/table-sort-search-demo"
    driver.get(url)
    driver.maximize_window()
    time.sleep(2)  # Allow page to load

    # Step 2: Locate the search box and input "New York"
    search_box = driver.find_element(By.XPATH, "//input[@type='search']")
    search_box.clear()
    search_box.send_keys("New York")
    time.sleep(2)  # Allow search results to update

    # Step 3: Validate the search results
    # Locate visible table rows
    visible_rows = driver.find_elements(By.XPATH, "//table[@id='example']/tbody/tr[not(contains(@style, 'display: none'))]")
    total_visible_rows = len(visible_rows)


    # Expected result
    expected_rows = 5

    # Validate the number of search results
    if total_visible_rows == expected_rows:
        print(f"Test Passed: Found {expected_rows} entries matching 'New York'.")
    else:
        print(f"Test Failed: Expected {expected_rows} entries, but found {total_visible_rows}.")

finally:
    # Clean up and close the browser
    driver.quit()